### ISSUE TITLE
OSMap doesn't respect menu item MaxLevel option in category list menu item

### ISSUE THREAD

**Issue by andrepereiradasilva** [OSTraining/OSMap#100]
### Problem

When you have a menu item "category list/blog" type and choose not to show the subcategories "Subcategory Levels", OSMap should respect that in XML and HTML site, but it doesn't.

### How to reproduce

1. New joomla install (disable all caching)
2. Install Com OSMap free version
3. Ativate only osmap content plugin, disable the others and choose to expand the categories
4. Create a sitemap in OSMap component
5. Create a menu item to HTML sitemap with sitemap as alias
6. Create a category "level1"
7. Create a category "level2" inside "level1"
8. Create a category list or category blog menu item pointing to the category "level1" and in the "Subcategory Levels" option put "None" 

9.Go to frontend domain.tld/sitemap or to the XML Sitemap and you will see that "level2" is being displayed and it shouldn't.

### Additional information

To solve in the case of "None" the only changes need are:
In https://github.com/OSTraining/OSMap/blob/master/src/extensions/plg_osmap_com_content/com_content.php#L299 replace
`if ($params['expand_categories'] && $id) {`
for
`if ($params['expand_categories'] && $id && $parent->params->get('maxLevel') != 0) {`

This would solve the problem described.

Of course, for instance when you select to show only 2 subcategory levels and you have subcategory 5 levels, a more complex solution is needed.

**Comment by andrepereiradasilva** [comment]
Closed has i made a PR https://github.com/OSTraining/OSMap/pull/102

**Comment by andergmartins** [comment]
Related to MAP-100
