### ISSUE TITLE
PHP Strict Standards issues

### ISSUE THREAD

**Issue by photodude** [OSTraining/OSMap#103]
* Declaration of OSMapXmlDisplayer::endMenu() should be compatible with OSMapDisplayer::endMenu(&$node) in components/com_osmap/views/xml/tmpl/default_class.php on line 233
* Declaration of OSMapXmlDisplayer::startMenu() should be compatible with OSMapDisplayer::startMenu(&$node) in components/com_osmap/views/xml/tmpl/default_class.php on line 233
* Declaration of OSMapXmlDisplayer::printNode() should be compatible with OSMapDisplayer::printNode(&$node) in components/com_osmap/views/xml/tmpl/default_class.php on line 233

It would be nice to see these Strict Standards issues resolved.

**Comment by andergmartins** [comment]
Thanks for report that, @photodude. It will be fixed in a next release

**Comment by photodude** [comment]
Thanks @andergmartins, and @nicksavov. Looking forward to the next release with this fix.
