### ISSUE TITLE
Error when using K2 plugin

### ISSUE THREAD

**Issue by shigri20** [OSTraining/OSMap#104]
Facing issue when using K2 plugin, I get the following error message whenever I try to view the XML sitemap:

XML Parsing Error: no element found
Location: http://www.suchtv.pk/urdu/index.php?option=com_osmap&view=xml&tmpl=component&id=1
Line Number 1, Column 1:
^

**Comment by htmgarcia** [comment]
Hi @shigri20,

Be sure you have last version of OSMap and Joomla updated.
If you keep having issues, please post the details in our forum: https://www.alledia.com/extensions/osmap/

Regards

**Comment by shigri20** [comment]
@htmgarcia i have installed  latest version of OSMAP in  two different Jommla 2.5 languages separately. I still facing this issue in mentioned above language.
