### ISSUE TITLE
cannot choose my sitemap when creating menu

### ISSUE THREAD

**Issue by romduf** [OSTraining/OSMap#105]
Joomla 3.4.5
Osmap : last free version
When i create a menu item, i can create a menu item to display xml sitemap but i CANNOT choose my sitemap... Somehow i see my sitemap in the list, but cannot select it... I have to click back button, as i am stuck when i try to select my sitemap.
Do you have a fix for that ? Because otherwise i cant use osmap at all.
Thanks in advance

![capture](https://cloud.githubusercontent.com/assets/16291412/11784519/033b1618-a27d-11e5-90aa-40ab20c1b9b5.JPG)

![capture2](https://cloud.githubusercontent.com/assets/16291412/11784518/0336b672-a27d-11e5-9d10-42a6f1e9714e.JPG)

Using firebug i get
index.php?option=com_osmap&view=sitemaps&layout=modal&tmpl=component&function=jSelectSitemap_jform_…:107 Uncaught TypeError: window.parent.jSelectSitemap_jform_request_id is not a function
index.php?

**Comment by htmgarcia** [comment]
Hi @romduf,

Reinstall OSMap, clear cache and try again.

Regards

**Comment by htmgarcia** [comment]
I can confirm the select sitemap works fine in my end.
If you keep having issues, please post the details in our forum: https://www.alledia.com/extensions/osmap/
