### ISSUE TITLE
Messy headings

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMap#12]
Can wait until after the first official launch ...

Not sure we need those stats. Definitely don't need "Hits" and definitely not data on both sitemaps

![osmap2](https://cloud.githubusercontent.com/assets/3868028/6476979/1632d558-c1eb-11e4-8079-6efec725c20a.png)

**Comment by andergmartins** [comment]
Agree, I think we can remove those and keep only the items count. But I think it may be better keep a param to re-enable and display the legacy stats again, if the user wants.

**Comment by andergmartins** [comment]
4053502d Hides the sitemap stats by default
