### ISSUE TITLE
Clean up links

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMap#13]
Can wait until after the first official launch ...

Give these more room so they're easier for users to see and access

![osmap3](https://cloud.githubusercontent.com/assets/3868028/6477011/6ff8afa4-c1eb-11e4-9e91-38cc73db7522.png)

**Comment by andergmartins** [comment]
The first block, with different sitemap links, not sure  how to clean it up

**Comment by stevejburge** [comment]
I'd say we should give each one it's own column. Maybe move the names to the table headings?

**Comment by andergmartins** [comment]
Ah, makes sense... tks

**Comment by andergmartins** [comment]
![joomla 34 - administration - sitemaps manager 2015-03-06 12-50-54](https://cloud.githubusercontent.com/assets/407131/6528268/9caeada8-c3ff-11e4-9602-dfb6c940aea4.png)

**Comment by stevejburge** [comment]
That's more like it, thanks.

Maybe change "Num. Items" to "Number of Links"

**Comment by andergmartins** [comment]
2a9153ac Improves header title

**Comment by andergmartins** [comment]
;) much better, tks
