### ISSUE TITLE
Import text

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMap#17]
"The migration process wipes any data found in OSMap tables, before start the import. Make sure you really can remove any existent data for OSMap"

Change this to:

"Please note: this migration will import your data to OSMap, but also remove any data found in the XMap."

**Comment by stevejburge** [comment]
Also, and this is a big one ...

![screen shot 2015-03-05 at 12 45 50 pm](https://cloud.githubusercontent.com/assets/3868028/6510705/a398b8e0-c335-11e4-8f7c-8646469e0f67.png)

**Comment by stevejburge** [comment]
And finally:

"The Xmap data was migrated successfully and it is now disabled! You can uninstall it after check the data. "

Should be:

The Xmap data was migrated successfully. You can now safely uninstall XMap."

**Comment by andergmartins** [comment]
@stevejburge what about:

2) "Are you really sure you can wipe current Xmap data, importing to OSMap?"
3) "The Xmap data was migrated successfully. You can now safely uninstall Xmap component, but keep the plugins."

**Comment by stevejburge** [comment]
2) "Are you really sure you want to wipe the current XMap data? The data will be imported to OSMap."
3) "Congratulations! The XMap data was migrated successfully. You can now safely uninstall the XMap component, but keep the plugins."

**Comment by andergmartins** [comment]
Sounds great! :) , applying that
