### ISSUE TITLE
Xmap reference in message after installing

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMap#18]
> Xmap plugin com_content was successfully updated

**Comment by htmgarcia** [comment]
@andergmartins @stevejburge do we need rebranding for those or are necessary to keep the preffix "x" for some reason?

**Comment by stevejburge** [comment]
Yes, would make sense to change the visible name, if not the file names

**Comment by andergmartins** [comment]
humm, they still are in the "xmap" plugin group, but I don't think it would hurt change the visible names

**Comment by htmgarcia** [comment]
Thanks guys!

**Comment by andergmartins** [comment]
Just checked, the message is automatic, It will require a little bit more work to get it corrected, but I can work that.

**Comment by andergmartins** [comment]
Related to #20

**Comment by andergmartins** [comment]
Moving to the 2.4.2 milestone to make sure we can launch tomorrow the 2.4.1

**Comment by andergmartins** [comment]
Fixed here: https://github.com/OSTraining/OSMap/issues/47
