### ISSUE TITLE
Empty title tag in HTML Sitemap menu item type

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMap#19]
*In frontend

**Comment by andergmartins** [comment]
Should we move the menu titles to h3 and add the title as h2? Right now, the menu titles are h2

**Comment by htmgarcia** [comment]
In my initial request was talking about the <title> tag. 

The main header title inside body should be h1 if I'm correct.

**Comment by andergmartins** [comment]
@htmgarcia github replaced the tag... is < title > ?

**Comment by htmgarcia** [comment]
lol
I didn't noticed. Yes, is the title tag.

**Comment by andergmartins** [comment]
Fixed on my tests, We can reopen if needed.

**Comment by htmgarcia** [comment]
Thanks @andergmartins !
