### ISSUE TITLE
New sitemap published by default

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMap#22]
By creating a new sitemap is set as unpublished

**Comment by andergmartins** [comment]
Humm, just tried twice and it is published.. are you coming from a fresh install? Do you have Xmap and is migrating, what is the scenery?

**Comment by nicksavov** [comment]
For me, it was published by default

**Comment by andergmartins** [comment]
I'm closing this issue, feel free to reopen if needed ;)

**Comment by htmgarcia** [comment]
I stil unpublished for me.

Steps to replicate:
Inside OSMap > New
The Status param is set as "unpublished"

Joomla 3.4

**Comment by nicksavov** [comment]
Ah, that was different than what I was expecting :) I thought you meant the default map when OSMap is initially installed.

Confirmed the issue.

**Comment by andergmartins** [comment]
Ah! Same here! Sorry Valentin, got it now

**Comment by andergmartins** [comment]
Fixed in #109

**Comment by htmgarcia** [comment]
Thanks guys!
