### ISSUE TITLE
Font problem in Joomla 2.5

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMap#26]
Looks like OSMap may need a slight CSS tweak in Joomla 2.5
![screen shot 2015-03-09 at 4 14 25 pm](https://cloud.githubusercontent.com/assets/3868028/6563440/89f37660-c677-11e4-8be1-5ef5ee79cef3.png)

**Comment by andergmartins** [comment]
Sorry, did you mean the icon, font for the menu?

**Comment by stevejburge** [comment]
Yes, OSMap makes a mess of the Joomla UI

**Comment by andergmartins** [comment]
Thanks, I will try again in another sites, couldn't reproduce in my dev site.

**Comment by andergmartins** [comment]
Ah, I see now, it happens in Firefox, but not in Chrome. I will fix, thanks

**Comment by andergmartins** [comment]
Fixed here: https://github.com/OSTraining/AllediaFreeDefaultFiles/commit/bfda0c9881a5025a4a7043ea5efb26bda77d1601
