### ISSUE TITLE
Keep backward compatibility with XMap plugins

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSMap#3]
We need a new plugin group, but wee need to keep backward compatibility with the xmap group. 
We should try to trigger both type of plugins (xmap first) and allow to disable the backward compatibility using a param.

**Comment by stevejburge** [comment]
Very smart thinking @andergmartins

**Comment by andergmartins** [comment]
Removing this, since it will be very difficult to predict 3rd part extensions compatibility

**Comment by andergmartins** [comment]
Ok, bringing it back... :)
