### ISSUE TITLE
SEO Glossary Plugin

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSMap#32]
[feedback]
My work around was turning that plugin off, which I think is fine but wanted to give you info that it throws an error and can't create the sitemap. 
[/feedback]
https://www.alledia.com/forum/osmap/72/

**Comment by andergmartins** [comment]
Ok, I will look for any update for that plugin and fix it manually if required.

**Comment by htmgarcia** [comment]
I can confirm the issue. 

Steps to reproduce:
https://secure.helpscout.net/conversation/79050463/11882/
Enable the plugin "Xmap - Seoglossary" (ver  2.0.1) and open the XML sitemap

**Comment by htmgarcia** [comment]
We suggested to the user request an update from the developer.
