### ISSUE TITLE
Xmap import keeps showing

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMap#35]
I imported the data to OSMap on OSTraining and removed XMap.

This time, when I ran the update, the import routine showed again:

![import](https://cloud.githubusercontent.com/assets/3868028/6604976/d33b2052-c802-11e4-895e-37858427e55b.png)

**Comment by nicksavov** [comment]
Looks like it's still installed, but just disabled. Check in administrator/index.php?option=com_installer&view=manage

**Comment by stevejburge** [comment]
Ooops, thanks Nick
