### ISSUE TITLE
Fix issues in review and contact review back

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSMap#40]
See:
http://extensions.joomla.org/extensions/extension/structure-a-navigation/site-map/osmap#rev-81758

**Comment by andergmartins** [comment]
1) I had not see this issue in a fresh joomla 3.4 without the weblinks component, but I'm double checking...

2) related to: #19

**Comment by andergmartins** [comment]
@nicksavov are you able to reproduce the first one?

2) fixed.

**Comment by nicksavov** [comment]
1) Check https://secure.helpscout.net/conversation/77236155/11709/ . We can ask for login details if needed.

**Comment by andergmartins** [comment]
Thanks @nicksavov
