### ISSUE TITLE
Rename plugins

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMap#47]
Currently the plugins are named in this format:
> Xmap - Content Plugin

change to:
> OSMap - Content Plugin

**Comment by andergmartins** [comment]
@htmgarcia, cool :) before merge this into master, let's implement the osmap plugin group #20. We can use your brnach

**Comment by htmgarcia** [comment]
@andergmartins cool!

I only changed the visible name, the pluging group is still "xmap"

**Comment by htmgarcia** [comment]
Thanks @andergmartins !
