### ISSUE TITLE
SH404SEF compatibility

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMap#49]
Is OSMap compatible with SH404SEF?
The URL manager created a different url for some menu items, which are not listed in the sitemap.

Related to: https://www.alledia.com/forum/osmap/96/
Example:
Menus > South-Carolina > South Carolina Business and Law Exam (menu item 128)

**Comment by stevejburge** [comment]
No, I think sh404SEF may cause some problems, unfortuantely.

sh404SEF will always control what the URLs are.

**Comment by htmgarcia** [comment]
Thanks @stevejburge 

Somebody build a plugin for this situation: http://www.de-wolff.eu/joomla/sh404sef/xmap-and-sh404sef.html
Download page: http://www.de-wolff.eu/download/joomla/sh404sef/xmap.html

Didn't tested btw.

**Comment by stevejburge** [comment]
I guess we list it, but with a disclaimer

**Comment by htmgarcia** [comment]
Wait, by checking the code of that extension I noticed is for Joomla 1.5.20.
