### ISSUE TITLE
Advanced param to allow display errors in xml

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMap#54]
In some cases there can be problems that break the XML, in order to fix it is required to disable this line and see which errors are behind: https://github.com/OSTraining/OSMap/blob/master/src/site/views/xml/view.html.php#L64

A param (by default disabled) to display errors, at least from the Global configuration > Server > Error reporting.

**Comment by andergmartins** [comment]
Right, agree that it should follow the global configuration, let's remove it

**Comment by htmgarcia** [comment]
@andergmartins I think a param in OSMap > options could be safer. 
In any case I'm easy.

**Comment by andergmartins** [comment]
Right, I see what you mean. Let's go with an OSMap Debug param

**Comment by htmgarcia** [comment]
Thanks guys! :)
