### ISSUE TITLE
Strict Standard errors in Hikashop Xmap plugin

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMap#55]
```
Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method xmap_com_hikashop::getTree() should not be called statically in /components/com_osmap/displayer.php on line 219
```

Related to: https://www.alledia.com/forum/osmap/102/

**Comment by hikashop-nicolas** [comment]
Having the getTree function of Xmap plugins not static has never been a problem with Xmap. If you advertise OsMap as compatible with Xmap plugins then it shouldn't be a problem either.
Now adding a static before the function definition to avoid the warning is possible and easy to do for us, but I'm worried of any backward compatibility with other site map tools like Xmap would might actually display an error because we would change that method to a static one.
Do you have any feedback on that ?

**Comment by andergmartins** [comment]
Hi @hikashop-nicolas, 
Thanks, I think you are right about the backward compatibility issues. We should not have any incompatibility issue with Xmap plugins, and we are constantly working to improve that. As I can see Xmap didn't force any pattern on the visibility of the getTree method, so we can find both, static and non-static, among different plugins. I just did some changes making sure we support both method visibilities.
I don't think you need to update the visibility of the getTree method in your plugin now, but thanks.

**Comment by andergmartins** [comment]
@hikashop-nicolas, I have fixed our extension but now I see what seems to be an issue in your plugin. I still have strict warnings about the methods visibility but now, pointing to the `hikashop::get(...` calls.

`Strict standards: Non-static method hikashop::get() should not be called statically, assuming $this from incompatible context in /var/www/plugins/xmap/com_hikashop/com_hikashop.php on line 78`

You will see that for the lines 78, 80, 89, 321.

You are calling the `get` method as static on that lines, but its declaration is non-static. I can't change anything to fix that on our side, can you check it please? Thanks!

**Comment by hikashop-nicolas** [comment]
Hi,

This has been fixed on our end. If you download again the plugin package on our website and install it on yours, you shouldn't get these warnings.

**Comment by andergmartins** [comment]
Thanks @hikashop-nicolas!

**Comment by htmgarcia** [comment]
Thanks guys!
