### ISSUE TITLE
SEF url for content inside category (Content plugin)

### ISSUE THREAD

**Issue by andrepereiradasilva** [OSTraining/OSMap#61]
If you have, for instance, a menu item with name "show-category-1" that lists a category named "category-1" (id 10) with two articles "article-1" (id 20) and "article-2" (id 30)..

The urls inside he sitemaps will be:
http://domain.tld/show-category-1
http://domain.tld/component/content/article/10-category-1/20-article1
http://domain.tld/component/content/article/10-category-1/30-article2

And it should be:
http://domain.tld/show-category-1
http://domain.tld/show-category-1/20-article1
http://domain.tld/show-category-1/30-article2

Thsi is a problem because the search engines then index two versions of the same page.

**Comment by htmgarcia** [comment]
Hi @andrepereiradasilva ,
thanks for the feedback!

May we have the url of the XML sitemap?

**Comment by andrepereiradasilva** [comment]
This is the structure
joomla 2.5.xx.

The structure of content is this:
- One category "News" for all languages
- Several news articles in english or french inside that category

And the menus:
french:
- One category blog menu item (homepage)
- One category list menu item "nouvelles"

english:
- One category blog menu item (homepage)
- One category list menu item "news"

I only noticed happening in joomla 2.5.xx.

**Comment by htmgarcia** [comment]
@andrepereiradasilva Thanks for the details!

I tested in a Joomla 2.5.28 installation with OSMap 3.0.2 
I wasn't able to reproduce the issue.

May you double check you are using the same OSMap version, please:
Go to Extensions > Extension manager > Manage
Search "OSMap" and check the version column

**Comment by andrepereiradasilva** [comment]
i have joomla 2.5.28 and OSMap 3.0.2

I noticed that i have yet another menu item that lists that category (category list).
That other menu item is only for logged in users.

**Comment by htmgarcia** [comment]
@andergmartins please update to OSMap 3.1.2
See if makes any difference.

**Comment by andrepereiradasilva** [comment]
In joomla 3 seems to be working ok.
