### ISSUE TITLE
Add logout button

### ISSUE THREAD

**Issue by andrepereiradasilva** [OSTraining/OSMap#62]
When a user is logged in to edit the sitemap, there should be a link to logout.

**Comment by andergmartins** [comment]
Just as reference:
![login](https://cloud.githubusercontent.com/assets/407131/12299312/4fdaa0f0-b9fd-11e5-99df-2d4438c62f1c.png)

![xml sitemap file 2016-01-13 13-54-34](https://cloud.githubusercontent.com/assets/407131/12299317/55b17e54-b9fd-11e5-8781-af18a79ca3b1.png)
