### ISSUE TITLE
Remove #cols option

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMap#67]
I can think we can remove this:
![screen shot 2015-04-22 at 9 07 34 am](https://cloud.githubusercontent.com/assets/3868028/7274956/129e129e-e8cf-11e4-9fc5-d55c6d6d9041.png)

Doesn't work well with the default Joomla 3 template:
![screen shot 2015-04-22 at 9 07 08 am](https://cloud.githubusercontent.com/assets/3868028/7274962/1aefca32-e8cf-11e4-8d06-fe0de4677f4d.png)

**Comment by htmgarcia** [comment]
+1 css class name and cols, at least
