### ISSUE TITLE
v3.0.2 update horrible

### ISSUE THREAD

**Issue by rgmears** [OSTraining/OSMap#72]
Just installed the recent update and now I have four copies of my site's contents listed one after the other ... after the other.

**Comment by andergmartins** [comment]
Hi @rgmears, I'm sorry to hear that you are having issues with our extension or maybe with any related extension. v3.0.2 is a 3 weeks old release, can you please try the latest one?

This is the first report we have for this issue, can you please describe more your setup, so we can try to reproduce and/or fix it?

* Joomla version
* Is your site content pure Joomla content, or are you using K2, or other component and its respective extension?

**Comment by rgmears** [comment]
Hi @andergmartins, thanks for the response.

I am not using K2. The only difference between two installations is one has Kunena on it, the other doesn't. Both are Joomla 3.4.1. 

Screenshots are attached. The first, short one is correct. I also tried v3.0.2. It didn't help. (Incidentally, I have introtext enabled for both site maps and, as you can see, it's not displaying.)

![ttrsitemap_good](https://cloud.githubusercontent.com/assets/4270063/7350094/f4810ee0-ecc2-11e4-8bde-e0fc04c77d62.png)
![ttrsitemap_not_good](https://cloud.githubusercontent.com/assets/4270063/7350095/f4850004-ecc2-11e4-9053-482b1ddf7ce5.png)

**Comment by htmgarcia** [comment]
Hi @rgmears ,

May we have the url of your XML and HTML sitemap?

**Comment by rgmears** [comment]
For the moment I have two versions of the site. One local, the other live. I made the update (which I am having troubles with) on the local installation and frankly am not eager to do it on the live site.

**Comment by rgmears** [comment]
Figured it out. I had disabled all of the plugins, even then uninstalled them. The new version re-installed them and enabled them all by default. Adjusting the content plugin &mdash; setting everything to NEVER &mdash; resolved the issue.

**Comment by rgmears** [comment]
BTW, the update link in the update section in Joomla! points to v3.0.2.

**Comment by htmgarcia** [comment]
@rgmears I'm glad to hear to find a workaround for this problem.

Try again the update process, last version available is v3.1.3. From Extensions > Extension manager > Update

**Comment by andergmartins** [comment]
Hi @rgmears, I wasn't able to reproduce this issue, and as you already have it fixed on your side I'm closing this. I agree that install and enabled by default all plugins every time you update OSMap is not ideal. We will implement a solution for that while working on this issue: https://github.com/OSTraining/OSMap/issues/81.

Thanks
