### ISSUE TITLE
Updates issue with OSMap 3.1.3

### ISSUE THREAD

**Issue by photodude** [OSTraining/OSMap#74]
The following "warnings" display on checking for updates in Joomla 3.4.1 with OSMap 3.1.3,  OS System 1.0.7, and Alledia Framework 1.3.0
```
Update: Could not open update site #18 "OSSystem", URL: https://deploy.ostraining.com/client/update/free/stable/plg_system_ossystem/extension.xml

Update: Could not open update site #19 "Alledia Framework", URL: https://deploy.ostraining.com/client/update/free/stable/lib_allediaframework/extension.xml
```

**Comment by photodude** [comment]
Closing as I realize this is an issue with just OS System 1.0.7, and Alledia Framework 1.3.0
- https://github.com/OSTraining/OSSystem/issues/4
- https://github.com/OSTraining/AllediaFramework/issues/9

**Comment by photodude** [comment]
This issue seems to have resolved itself. Last check for updates did not return  the warning about not being able to open the update site.

related issues are posted in the forum
https://www.alledia.com/forum/osmap/162/
https://www.alledia.com/forum/osmap/146/

**Comment by nicksavov** [comment]
Hi photodude,

Thanks for checking on this one! We added an intermediate certificate in the Nginx configuration on our server and that resolved the original issue.

Thanks again, photodude!

Cheers

**Comment by photodude** [comment]
@nicksavov Your welcome, thanks for figuring out a work around for the issue.

All the best
