### ISSUE TITLE
Missing clearfix

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMap#77]
From Radovan J ...

hi,

thanks for free replacement of xmap component. 

but you have bug in your component: if you have - in html site map - 2 or more columns, they are not "cleared", I mean, you have div floating to left, but after that, you must them "clear"... now you have broken template.

please see attached images

thanks for fixing it soon

best regards,
radovan

PS: OSMap 3.1.3, Joomla 3.4.1, template: modification of Protostar template (on attached images) but with same (wrong) results with default joomla Protostar template.
![sitemap - 1 column](https://cloud.githubusercontent.com/assets/3868028/7912475/d5189b16-0835-11e5-8d37-d5b0e3a0eaa8.jpg)
![sitemap - 2 columns](https://cloud.githubusercontent.com/assets/3868028/7912478/db2b4260-0835-11e5-9bd6-45298e9ca244.jpg)

**Comment by htmgarcia** [comment]
Confirmed the issue and fixed.
