### ISSUE TITLE
Trigger onPrepareContent before get images

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSMap#82]
If images are added to an article through a content plugin, they are missed on the images site map. Google is not seeing that images.

We can trigger the onContentPrepare event before grab images from articles. That can makes the process too heavy, for many articles. Let's add a param, where user can choose trigger or not the event.

`JHtml::_('content.prepare', $text);`

**Comment by htmgarcia** [comment]
+1 make sense
