### ISSUE TITLE
XML Parsing Error: not well-formed

### ISSUE THREAD

**Issue by prophoto** [OSTraining/OSMap#89]
XML Parsing Error: not well-formed
Location: /index.php?option=com_osmap&view=xml&layout=xsl&tmpl=component&id=1&filter_showtitle=&filter_showexcluded=
Line Number 306, Column 33:

Upgraded from xmap and now seeing this issue. Installed v3.1.5 today. Turned off beautify xml and it fixed the issue.

**Comment by htmgarcia** [comment]
Hi @prophoto, 

Turning off beautify xml is there for that very reason. 
I'm glad the sitemap is working for you :)
