### ISSUE TITLE
Language changes

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMap#9]
"Installing Xmap plugin com_weblinks was successful"

"OSMap have detected" should be "OSMap has detected"

**Comment by andergmartins** [comment]
@stevejburge about "Installing Xmap plugin com_weblinks was successful" would be better something like: "Xmap plugin com_weblinks successfully installed."

**Comment by htmgarcia** [comment]
com_weblinks was removed in Joomla 3.4. Should we think this plugin as a separate addon in the JED? Like OSMap for weblinks. 
This may potentially works as a way to promote OSMap.

Just an idea.

**Comment by andergmartins** [comment]
It would be good, but I think we can't, since it was available for free in Xmap before. We promised to users to keep free what was already free

**Comment by htmgarcia** [comment]
Good point. I'm sold :)
