### ISSUE TITLE
Alias menu item issue

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSMap#90]
Video explanation: http://youtu.be/SPYRs-AJbow
Original report: https://github.com/OSTraining/OSMap/issues/70#issuecomment-136611966

**Comment by JoomFX** [comment]
@htmgarcia Hey Valentin, any update regarding this issue?

**Comment by htmgarcia** [comment]
@JoomFX Hi Ivo, we have this issue in the radar. However our lead developer got bussy in other tasks.
We will be back as soon as possible.

My apologies for the inconvenience

**Comment by JoomFX** [comment]
@htmgarcia No problem mate. Thanks for the update :)

**Comment by JoomFX** [comment]
@htmgarcia Hey Valentin,

Sorry to bother you again, but could you please update me on the status of this issue?
It was opened more than 2 months ago.
Thanks :)

**Comment by andergmartins** [comment]
Hi @JoomFX 

Sorry for the huge delay on this fix. It was a little bit difficult to debug, but easy to fix after find out the root of the failure. 
I will be releasing a new version today. Let us know if it works for you.
Thank you for the patience.
