### ISSUE TITLE
Error ( or update ) message after uninstall all Osmap plugins 

### ISSUE THREAD

**Issue by cyrilmaillet** [OSTraining/OSMap#91]
Hi,

im very nervous, Osmap show me a message with an error after i have uninstall all the program from my joomla 3.4.4 .

It indicate " alledia os not found " , or if i dont remove alledia framework it indicate to update .

I want remove the full program from my joomla and dont want any screen popup ...

How i can do that ?

**Comment by htmgarcia** [comment]
Hi @cyrilmaillet 

Go to Extensions > Manage > look for the extensions you don't need and uninstall it.
I recommend a backup before doing any change, just in case

**Comment by cyrilmaillet** [comment]
Im not a newbie developer, i have lot of experience ...

i already know i have to go to  Extensions > Manage > for uninstall your  
program , and this is what i do.

But when i uninstall Alledia framework from plugins , it show this error  
messages everywhere !

How i can remove this message ?



Le Wed, 16 Sep 2015 22:12:24 +0200, Valentín <notifications@github.com> a  
écrit:

>
> Hi @cyrilmaillet
> Go to Extensions > Manage > look for the extensions you don't need and  
> uninstall it.
> I recommend a backup before doing any change, just in case
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Cyril Maillet
35 rue des fontaines 39200 Chevry
FRANCE
07 52 03 02 25

www.cyrilmaillet.fr.cr

**Comment by htmgarcia** [comment]
Hi @cyrilmaillet,
The Alledia framework is required when you have any Alledia extension. That's probably why you see that message.

Do you have other extensions that requires Alledia framework? Please double check

**Comment by cyrilmaillet** [comment]
I have just installed osmap and remove the 6 or 7 osmap plugins and the  
alledia framework, so please script me all things i have to uninstall

Le Thu, 17 Sep 2015 16:45:46 +0200, Valentín <notifications@github.com> a  
écrit:

>
> Hi @cyrilmaillet,
> The Alledia framework is required when you have any Alledia extension.  
> That's probably why you see that message.
>
> Do you have other extensions that requires Alledia framework? Please  
> double check
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Cyril Maillet
35 rue des fontaines 39200 Chevry
FRANCE
07 52 03 02 25

www.cyrilmaillet.fr.cr

**Comment by vickythomas** [comment]
Cyrilmaillet, did you find your answer?  I had a similar issue after uninstalling OSMap.  Then, I searched  on 'OS' in the extension manager and found a few more related (unpublished) plugins.  After I uninstalled all those, the error message disappeared.

**Comment by cyrilmaillet** [comment]
Hi Vickythomas, ... no i have try to find how i can remove this f....... framework after all uninstalled plugin but it appear not to be possible to remove the message , because the program seem to modify the core of joomla.

So i hope for you, you have backup your work not too far before you install this automatic sitemap program who dont work good.

I think this program have a malicious spyware attached, so warning about automatic program who access to our server !

**Comment by vickythomas** [comment]
Hi.  In my case, after I uninstalled all the plugins, the message did go away,so all is good here.  This was on a J2.5 site.  @htmgarcia can you tell him where all the files are so he can manually remove them?

**Comment by nicksavov** [comment]
Hi cyrilmaillet,

It does *NOT* modify the core of Joomla and there is *NO* spyware within it.

As mentioned by htmgarcia, the Alledia Framework is a plugin that's required for OSMap. It's a shared library for our Alledia extension. If you don't want to have it on your site, simply uninstall it and our Alledia extensions.

The code is open source on your site. So you can look through the code to verify there is no spyware on it and that it doesn't modify the Joomla core. Futhermore, the code is available publicly at https://github.com/OSTraining/AllediaFramework/

Hope this helps! Let us know if you have any questions and we'll be glad to answer.

**Comment by htmgarcia** [comment]
Hi @vickythomas ,

The files are stored inside the plugins and libraries/allediaframework folders, however uninstalling OSMap from the Extension manager (through Extensions > Manage > Manage) is what removes the files.

Hopes this helps

**Comment by cyrilmaillet** [comment]
Hi,

im sorry but i have uninstall all alledia things in extension , but the message appear everywhere
![capture plein ecran 05122015 213024 bmp](https://cloud.githubusercontent.com/assets/12858108/11609995/285c3f1e-9b96-11e5-818a-0d8c93055f1b.jpg)

**Comment by htmgarcia** [comment]
@cyrilmaillet uninstall "System - OSSystem" plugin as well.

**Comment by cyrilmaillet** [comment]
Ok, it work , i have never seen this "System - OSSystem"

**Comment by nicksavov** [comment]
Great! Glad you got it working, Cyril!
