### ISSUE TITLE
Problem with javascript - missing ";"

### ISSUE THREAD

**Issue by andrepereiradasilva** [OSTraining/OSMap#94]
In this line a ";" is missing
- this.onComplete = checkExcludeResult

should be
- this.onComplete = checkExcludeResult;

https://github.com/OSTraining/OSMap/blob/master/src/site/views/html/tmpl/default.php#L32

This problem happens when you mimify the HTML/javascript code.

**Comment by nicksavov** [comment]
Thanks! It's fixed now:
https://github.com/OSTraining/OSMap/commit/61764c7aee65c2623e14a06f7cdf97bc159bbc51

The fix will be available in the next release.
