### ISSUE TITLE
Add ACL 

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSMap#96]
Users should be able to control who is able to see or operate the component

**Comment by htmgarcia** [comment]
+1

**Comment by htmgarcia** [comment]
Maybe as a pro feature?

**Comment by andergmartins** [comment]
Yes ;) agree. It is already implemented, btw. Just testing...

**Comment by nicksavov** [comment]
I think it should be in the free version. It seems like a standard Joomla feature that should come with every component.

**Comment by andergmartins** [comment]
Ok
