### ISSUE TITLE
HTML sitemap issue (two menu item pointing to the same article)

### ISSUE THREAD

**Issue by andrepereiradasilva** [OSTraining/OSMap#99]
### Problem

Some items are missing in the HTML sitemap (but they exist in XML sitemap with the same `<uid>`).

This happens when you have two or more 2 menu items (single article type) in the same menu level that point to the same article.
This shouldn't happen because they are different pages (urls).

### How to replicate

1. New joomla install 
2. Install Com OSMAP free
3. Create a sitemap in OSMAP compoent
4. Ativate only osmap content plugin, disable the others
5. Create some Single Article menu items pointing to the same article
6. Create a menu item to HTML sitemap with sitemap as alias
7. Disable all caching and clean cache
8. Go to frontend domain.tld/sitemap and you will see only the first of the menu items with the same article id are displayed.

### Aditional info

This happens only when you have osmap content plugin enabled, if you disabled it will show all menu items as it should.

If you comment this line https://github.com/OSTraining/OSMap/blob/master/src/extensions/plg_osmap_com_content/com_content.php#L122 it will show the menu items.

I think you need the menu item id also in the node uid for this to work.

Maybe replacing `$node->uid = 'com_contenta' . $id;` for `$node->uid .= 'com_contenta' . $id;` will do the job. The same will apply to the category part

**Comment by andrepereiradasilva** [comment]
> Maybe replacing $node->uid = 'com_contenta' . $id; for $node->uid .= 'com_contenta' . $id; will do the job. The same will apply to the category part.«

Tested and it worked.
@andergmartins Can you check?

**Comment by andrepereiradasilva** [comment]
Closed has i made a PR https://github.com/OSTraining/OSMap/pull/102

**Comment by andergmartins** [comment]
Related to MAP-99
